export const darkTheme ={
    palette: {
        themePrimary: '#39ff13',
        themeLighterAlt: '#f7fff6',
        themeLighter: '#dfffd9',
        themeLight: '#c4ffb8',
        themeTertiary: '#88ff71',
        themeSecondary: '#51ff2e',
        themeDarkAlt: '#34e610',
        themeDark: '#2cc20e',
        themeDarker: '#208f0a',
        neutralLighterAlt: '#27282b',
        neutralLighter: '#2f3133',
        neutralLight: '#3c3e41',
        neutralQuaternaryAlt: '#45464a',
        neutralQuaternary: '#4b4d51',
        neutralTertiaryAlt: '#686a6f',
        neutralTertiary: '#c8c8c8',
        neutralSecondary: '#d0d0d0',
        neutralPrimaryAlt: '#dadada',
        neutralPrimary: '#ffffff',
        neutralDark: '#f4f4f4',
        black: '#f8f8f8',
        white: '#1e1f21',
    }
};